version: "3.9"

services:

  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis

  redis:
    image: redis:7
    container_name: redis_server
    ports:
      - "6379:6379"